var msb_data = [
{'type':'food','title':'apples','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'food','title':'bread','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'food','title':'bacon','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'food','title':'jelly beans','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'food','title':'brocolli','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'food','title':'beans','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'food','title':'carrots','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'food','title':'dill pickles','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'food','title':'eggs','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'food','title':'frozen chicken','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'nonfood','title':'pens','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'nonfood','title':'paper','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'nonfood','title':'screwdriver','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'nonfood','title':'pliers','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'nonfood','title':'t-shirt','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'nonfood','title':'boxers','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'nonfood','title':'stapler','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'nonfood','title':'lamp shade','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'nonfood','title':'AA Batteries','quantity':1,'pricePerUnit':1.00,'selected': true},
{'type':'nonfood','title':'AAA Batteries','quantity':1,'pricePerUnit':1.00,'selected': false},
{'type':'nonfood','title':'AAA Batteries','quantity':1,'pricePerUnit':1.00,'selected': false}
];
